# Generated by Django 3.0.6 on 2020-05-18 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamtragch_Baiguulgiin_Zuuchlah_Uilchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hurimiin_Yslol_Uilchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Neriin_Buteegdehuun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Surgalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tureesiin_Uilchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamtragch', models.ManyToManyField(related_name='_cart_hamtragch_+', to='WeddingApp.Hamtragch_Baiguulgiin_Zuuchlah_Uilchilgee')),
                ('neriin', models.ManyToManyField(related_name='_cart_neriin_+', to='WeddingApp.Neriin_Buteegdehuun')),
                ('surgalt', models.ManyToManyField(related_name='_cart_surgalt_+', to='WeddingApp.Surgalt')),
                ('turees', models.ManyToManyField(related_name='_cart_turees_+', to='WeddingApp.Tureesiin_Uilchilgee')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yslol', models.ManyToManyField(related_name='_cart_yslol_+', to='WeddingApp.Hurimiin_Yslol_Uilchilgee')),
            ],
        ),
    ]
