# Generated by Django 3.0.6 on 2020-05-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamtragch_Baiguulgiin_Zuuchlah_Uilchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hurimiin_Yslol_Uilchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Neriin_Buteegdehuun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Surgalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tureesiin_Uilchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
    ]
