# Generated by Django 3.0.6 on 2020-05-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0002_auto_20200525_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='start',
            field=models.CharField(max_length=250),
        ),
    ]
